online_store/online_store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include(('shop.urls', 'online_store'), namespace='shop')),
    path('users/', include(('users.urls', 'online_store'), namespace='users'))
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += staticfiles_urlpatterns()

online_store/shop/urls.py
from unicodedata import name
from django.urls import URLPattern, path
from . import views

urlpatterns = [
    path ('products/', views.products_list, name = 'products_list'),
    path ('cart/', views.cart, name='cart'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_item/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('rate_product/<int:pk>', views.rate_product, name='rate_product'),
    path('orders/', views.orders, name = 'orders')
]

online_store/users/urls.py
import imp
from unicodedata import name
from django import views
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
]

online_store/shop/models.py
from ast import Or
import imp
from itertools import product
import re
from django.db import models
from django.contrib.auth.models import User
from django.urls import clear_script_prefix

class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    slug = models.SlugField(unique=True)
    is_new = models.BooleanField(default=False)
    is_discounted = models.BooleanField(default=False)
    category = models.ForeignKey('shop.Category', on_delete=models.CASCADE, default=None)
    brand = models.ForeignKey('shop.Brand', on_delete=models.CASCADE)
    thumb = models.PositiveSmallIntegerField(default='default_product.jpg', null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'shop_products'


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_categories'


class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'shop_brands'

class Slide(models.Model):
    image = models.ImageField(default='slide.jpg')

class CartItem(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    def total_price(self):
        return self.product.price * self.quantity

class Order(models.Model):
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    total_price = models.IntegerField()
    customer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Order {self.id}"

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return f" {self.product} x{self.amount} - {self.order.customer.username}"

RATE_CHOICES = [
    (1, '1 - Trash'),
    (2, '2 - Bad'),
    (3, '3 - Ok'),
    (4, '4 - Good'),
    (5, '5 - Excellent')
]

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=3000, blank=True)
    rate = models.CharField(choices=RATE_CHOICES, null=True, max_length=255)

    def __str__(self):
        return self.user.username

online_store/shop/forms.py
from django import forms
from .models import Order, Review, RATE_CHOICES
from .bulma_mixin import BulmaMixin

class OrderForm(BulmaMixin, forms.ModelForm):
    address = forms.CharField(label = 'Write your adress')
    phone = forms.CharField(label='Write your phone')

    class Meta:
        model = Order
        fields = ['address', 'phone']

class RateForm(BulmaMixin, forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'textarea'}),
        label='Leave yor review here...')
    rate = forms.ChoiceField(
        choices=RATE_CHOICES,
        required=True,
        label='Rate product form 1 to 5'
    )

    class Meta:
        model = Review
        fields = ['text', 'rate']

online_store/shop/views.py
from django.shortcuts import render, redirect
from .models import Product
from .models import *
from django.contrib.auth.decorators import login_required
from . import forms
from django.db.models import Q


@login_required(login_url='/users/sign_in')
def products_list(request):
    category = request.GET.get('category')
    brand = request.GET.get('brand')
    product_id = request.GET.get('product')
    search_value = request.GET.get('search')

    if product_id:
        product = Product.objects.get(id=product_id)
        cart_item = CartItem.objects.filter(product=product)
        if not cart_item:
            cart_item = CartItem.objects.create(
                customer=request.user,
                product=product,
                quantity=1
            )
            cart_item.save()
            return redirect('shop:products_list')

        for item in cart_item:
            item.quantity += 1
            item.save()

    products = Product.objects.all()
    slides = Slide.objects.all()

    products = products.filter(category=category) if category else products
    products = products.filter(brand=brand) if brand else products
    products = products.filter(
        Q(title__icontains=search_value) |
            Q(description__icontains=search_value)) if search_value else products
        
    return render(request, 'products.html', {'products': products, 'slides': slides})


def cart(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    total_price = sum([item.total_price() for item in cart_items])
    total_quantity = sum([item.quantity for item in cart_items])

    return render(
        request,
        'cart.html',
        {'cart_items': cart_items,
         'total_price': total_price,
         'total_quantity': total_quantity}
    )


def delete_cart_item(request, pk):
    cart_item = CartItem.objects.get(pk=pk).delete()
    return redirect('shop:cart')


def edit_cart_item(request, pk):
    cart_item = CartItem.objects.get(pk=pk)
    action = request.GET.get('action')

    if action == 'decrement' and cart_item.quantity > 0:
        if cart_item.quantity == 1:
            cart_item.delete()
            return redirect('shop:cart')
    cart_item.quantity += 1
    cart_item.save()
    return redirect('shop:cart')


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    return render(request, 'product_detail.html', {'product': product})


def create_order(request):
    cart_items = CartItem.objects.filter(customer=request.user)
    total_price = sum([item.total_price() for item in cart_items])
    total_quantity = sum([item.quantity for item in cart_items])

    form = forms.OrderForm(request.POST)

    if request.method == 'POST' and form.is_valid() and cart_items:
        order = Order.objects.create(
            address=request.POST.get('address'),
            phone=request.POST.get('phone'),
            total_price=total_price,
            customer=request.user
        )
        for cart_item in cart_items:
            OrderProduct.objects.create(
                order=order,
                product=cart_item.product,
                amount=cart_item.quantity,
                total=cart_item.total_price()
            )
        cart_items.delete()
        return redirect('shop:cart')

    return render(request, 'create_order.html', {'cart_items': cart_items,
                                                 'total_price': total_price,
                                                 'total_quantity': total_quantity,
                                                 'form': form})
def rate_product(request, pk):
    product = Product.objects.get(pk=pk)
    reviews = Review.objects.filter(user=request.user)

    if request.method == 'POST':
        form = forms.RateForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.user = request.user
            rating.product = product
            rating.save()
            return redirect('shop:rate_product')
    form = forms.RateForm()
    return render(request, 'rate_product.html',
                      {'form': form, 'product': product, 'reviews': reviews})


def orders(request):
    orders_list = Order.objects.filter(customer=request.user)
    return render(request, 'orders.html', {'orders': orders_list})

online_store/shop/templates/base_layout.html
{% load static %}
{% load brands %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <link rel="stylesheet" href="{% static 'static/bulma.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>

<body>
    <section class="hero">
        <div class="hero-head">
            {% if user.is_authenticated %}
            <nav class="navbar" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a class="navbar-item" href="{% url 'shop:products_list' %}">
                        <img src="https://mondaylabs.ru/static/img/logo-monday.svg" width="112" height="28">
                    </a>
                    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                        data-target="navbarBasicExample">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>
                {% brands %}
                <div class="navbar-end">
                    <div class="navbar-item mt-4">
                    <form action="{% url 'shop:products_list' %}">
                        <div class="field has-addons">
                            <div class="control">
                                <input class="input" type="search" name="search" placeholder="Find a product...">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit">
                                    Search
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <a class="navbar-item order" href="{% url 'shop:orders' %}">
                    <button class="button is-dark">
                        Orders
                    </button>
                </a>
                <a href="{% url 'shop:cart' %}" class="navbar-item order">
                    <button class="button is-success"> 
                        <ion-icon name="cart-outline" class="mr-2"></ion-icon>
                        Cart
                    </button>
                </a>
            
                    <span class="navbar-item">
                        <button class="button is-warning">
                            Welcome {{ user }}
                        </button>
                    </span>
                    <span class="navbar-item">
                        <a href="{% url 'users:sign_out' %}" class="button is-danger">Sign out</a>
                    </span>
                </div>
            </nav>
            {% endif %}
        </div>
        <div class="hero-body">
            {% block auth %}
            {% endblock %}

            {% block slider %}
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.css">
    </script>
    <script>
        bulmaCarousel.attach('#carousel-demo', {
            slidesToScroll: 1,
            slidesToShow: 1,
            infinite: true,
        });
    </script>
</body>

</html>

online_store/shop/templates/brands.html
{% for brand in brands %}
    <a href="{% url 'shop:products_list' %}?brand={{ brand.pk }}" class="navbar-item">
        {{ brand }}
    </a>
{% endfor %}

online_store/shop/templates/cart.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}
<div class="card mt-4 p-4 has-text-weight-bold is-size-4">
    <a href="{% url 'shop:products_list' %}" class="button has-text-left is-danger">
        Back to main page
    </a>
    {% if cart_items %}
    <a href="{% url 'shop:create_order' %}" class="button has-text-right is-info">Checkout</a>
    {% endif %}
    <hr>
    <div class="columns has-text-centered">
        <div class="column">
            <div class="content"> Items: {{ total_quantity }}
            </div>
        </div>
        <div class="column">
            <div class="comtent">
                Total: {{ total_price }} sum
            </div>
        </div>
    </div>
</div>
<div class="card p-5">
    <div class="content">
        {% if cart_items %}
        <table class="table has-text-centered">
            <thead>
                <tr>
                    <th></th>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>
                        <img src="{{ item.product.thumb.url }} " alt="" width="100" height="100">
                    </td>
                    <td>{{ item }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.quantity }}
                        <div class="quantity ml-3">
                            <a href="{% url 'shop:edit_cart_item' item.pk %}?action=increment">
                                <img src="{% static 'uploads/arrow-up.png' %}" alt="" class="arrows">
                            </a>
                            <a href="{% url 'shop:edit_cart_item' item.pk %}?action=decrement">
                                <img src="{% static 'uploads/arrow-down.png' %}" alt="" class="arrows">
                            </a>
                        </div>
                    </td>
                    <td>{{ item.total_price }} sum</td>
                    <td>
                        <a href="{% url 'shop:delete_cart_item' item.pk %}" style="font-size: 20px; color: black;">
                            <ico-icon name="trash-outline"></ico-icon>
                            <button class="button">
                                onet
                            </button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="title has-text-centered" >
            Nothing added
        </p>
        {% endif %}

    </div>
</div>
{% endblock %}

online_store/shop/templates/categories.html
<aside class="menu has-background-primary-light p-4" style="height: 750px; border-radius: 10px">
    <p class="menu-label is-size-3">
        Categories
    </p>
    <ul class="menu-list">
        {% for category in categories %}
            <li>
                <a href="{% url 'shop:products_list' %}?category={{ category.pk }}" class="dropdown-item is-size-5">
                    {{ category }}
                </a>
            </li>
        {% endfor %}
    </ul>
 </aside>

online_store/shop/templates/create_order.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <div class="columns">
        <div class="column">
            <div class="box">
                <form action="{% url 'shop:create_order' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="title">
                        Shipping information
                    </div>
                    {% for field in form %}
                    <div class="field">
                        <label for="{{ field.id_for_label }}" class="label">
                            {{ field.label }}
                        </label>
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button class="button is-success is-fullwidth" type="submit">
                        Submit
                    </button>
                </form>
            </div>
        </div>
        <div class="column is-6">
            <div class="box">
                <a class="button is-danger" href="{% url 'shop:cart' %}">Back to cart</a>
                <hr>
                <div class="title">Order Summary</div>
                <table class="table is-fullwidth">
                    <thead>
                        <tr class="has-text-weight-bold">
                            <td></td>
                            <td>Product</td>
                            <td>Price</td>
                            <td>Quantity</td>
                            <td>Total</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                            <tr>
                                <td>
                                    <img src="{{ item.product.thumb.url }}" width="50" height="50" alt="">
                                </td>
                                <td>{{ item }}</td>
                                <td>{{ item.product }} sum</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.total_price }} sum</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
               <p class="title is-4">
                Total: {{ total_price }} sum
               </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

online_store/shop/templates/edit_profile.html
{% extends 'base_layout.html' %}
{% block auth %}
<div class="columns is-centered">
    <div class="column is-4">
        <div class="box has-background-info-light">
            <form class="form" method="post" enctype="multipart/form-data">
                <h1 class="title has-text-centered is-2">Edit Profile</h1>
                {% csrf_token %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
                {% endfor %}
                <button class="button is-primary is-fullwidth" type="submit">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

online_store/shop/templates/file_input.html
<div class="file">
    <label class="file-label">
        <input type="{{ widget.type }}" class="file-input" name="{{ widget.name }}"
            {% if widget.value != None %}
                value="{{ widget.value|stringformat:'s' }}"
            {% endif %}
            {% include "django/forms/widgets/attrs.html" %}>
            <span class="file-cta">
                <ion-icon name="cloud-upload-outline" class="mr-2"></ion-icon>
                <span class="file-label">
                    Choose a file…
                </span>
            </span>
    </label>
 </div>

online_store/shop/templates/orders.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="card p-5">
        <div class="content">
            {% if orders %}
            <div class="title has-text-centered">My recent orders</div>
            <table class="table has-text-centered">
                <thead>
                    <tr>
                        <th>Order number</th>
                        <th>Products</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Payed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order }}</td>
                        <td>
                            {% for order_product in order.order_products.all %}
                            <a href="{% url 'shop:product_detail' order_product.product.pk %}">
                                {{ order_product }}
                            </a>
                            {% endfor %}
                        </td>
                        <td>{{ order.total_price }} sum</td>
                        <td>Into consideration</td>
                        <td>Not payed</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class="title has-text-centered">Nothing ordered yet</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

online_store/shop/templates/product_detail.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
   <div class="section product-detail">
       <div class="columns is-flex is-align-items-center">
           <div class="column">
               <div class="box">
                   <figure class="image product-detail-image">
                       <img src="{{ product.thumb.url }}" alt="Placeholder image">
                   </figure>
               </div>
           </div>
           <div class="column">
               <div class="content">
                   <p class="title is-size-2">
                       {{ product.title }}
                       {% if product.is_new %}
                           <span class="tag is-danger">New!</span>
                       {% endif %}
                       {% if product.is_discounted %}
                           <span class="tag is-primary">Discount!</span>
                       {% endif %}
                   </p>
                   <p class="title is-size-3 has-text-info">{{ product.price }} sum</p>
                   <p class="title is-size-5 has-text-grey-light">0 отзывов</p>
                   <p class="title">Brand: {{ product.brand }}</p>
                   <p class="title has-text-grey-light is-size-4">Наличие: Есть в наличии</p>
                   <p class="title is-size-4">
                       Поделится:
                       <span class="is-size-4 mx-3">
                           <a href="#">
                               <ion-icon name="logo-whatsapp" class="order"></ion-icon>
                           </a>
                           <a href="#">
                               <ion-icon name="logo-youtube" class="order"></ion-icon>
                           </a>
                           <a href="#">
                               <ion-icon name="logo-facebook" class="order"></ion-icon>
                           </a>
                       </span>
                   </p>
               </div>
           </div>
       </div>
   </div>
{% endblock %}

online_store/shop/templates/products.html
{% extends 'base_layout.html' %}
{% load categories %}
{% block slider %}
<div class="container-slide">
    <div id="carousel-demo" class="carousel">
        {% for slide in slides %}
        <div class="item-1">
            <img class="slider-img" src="{{ slide.image.url }}" alt="">
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-one-fifth">
        {% categories %}
    </div>
    <div class="column">
        <div class="columns is-multiline is-centered">
            {% for product in products %}
            <div class="column is-4">
                <div class="card" style="min-height: 620px">
                    <a href="{% url 'shop:product_detail' product.pk %}">
                        <div class="card-image">
                            <figure class="image">
                                <img src="{{ product.thumb.url }}" alt="Placeholder image">
                            </figure>
                            <div class="has-text-right m-3">
                                {% if product.is_new %}
                                <span class="tag is-danger">New!</span>
                                {% endif %}
                                {% if product.is_discounted %}
                                <span class="tag is-primary">Discount!</span>
                                {% endif %}
                            </div>
    
                        </div>
                    </a>
                    <div class="card-content">
                        <div class="media">
                            <br>
                            <div class="media-content">
                                <p class="title is-4">{{ product }}</p>
                            </div>
                        </div>
                        <div class="content has-text-weight-bold">
                            <div class="columns">
                                <div class="column">
                                    {{ product.price }} sum
                                </div>
                                <div class="column has-text-right">
                                    <a href="{% url 'shop:products_list' %}?product={{ product.id }}">
                                        <ion-icon name="cart-outline" class="order"></ion-icon>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

online_store/shop/templates/rate_product.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<div class="section">
    <div class="columns is-flex is-align-items-center">
        <div class="column">
            <div class="box">
                <figure class="image product-detail-image">
                    <img src="{{ product.thumb.url }}" alt="Placeholder image">
                </figure>
            </div>
        </div>
        <div class="column">
            <div class="box">
                <div class="content">
                    <p class="title is-size-2">
                        {{ product.title }}
                        {% if product.is_new %}
                        <span class="tag is-danger">New!</span>
                        {% endif %}
                        {% if product.is_discounted %}
                        <span class="tag is-primary">Discount!</span>
                        {% endif %}
                    </p>
                    <p class="title is-size-5 has-text-grey-light">{{ product.description }}</p>
                    <form action="{% url 'shop:rate_product' product.pk %}" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        {% if field.name == 'rate' %}
                        <div class="select is-fullwidth my-2">
                            <label for="{{ field.id_for_label }}" class="label">
                                {{ field.label }}
                            </label>
                            {{ field }}
                        </div>
                        {% else %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">
                                {{ field.label }}
                            </label>
                            {{ field }}
                        </div>
                        {% endif %}
                        {% endfor %}
                        <button class="button is-fullwidth is-success" type="submit">
                            Submit
                        </button>
                        <a href="{% url 'shop:product_detail' product.pk %}" class="button is-danger">
                            Back to {{ product.title }}
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="section">
    {% if reviews %}
        <div class="title is-size-3 has-text-centered">Reviews of other clients</div>
        <div class="columns is is-multiline is-centered">
            {% for review in reviews %}
                <div class="column is-4">
                    <div class="card">
                        <div class="card-content">
                            <div class="media">
                                <div class="media-left">
                                    <figure class="image is-48x48">
                                        <img src="https://www.winhelponline.com/blog/wp-content/uploads/2017/12/user.png"
                                             alt="Placeholder image" class="is-rounded">
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <p class="title is-size-4">{{ review.user.first_name }}</p>
                                    <p class="subtitle">@{{ review.user }}</p>
                                </div>
                            </div>
                            <div class="content">
                                <div>
                                    {{ review.rate }}/5
                                    <ion-icon name="star-outline"></ion-icon>
                                    <span class="mx-2 has-text-grey-light">{{ review.date }}</span>
                                </div>
                            </div>
                            <div class="subtitle has-text-grey">
                                {{ review.text }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="title is-size-3 has-text-centered">No reviews yet. Be first to leave one</div>
    {% endif %}
</div>



{% endblock %}