online_store/online_store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include(('shop.urls', 'online_store'), namespace='shop')),
    path('users/', include(('users.urls', 'online_store'), namespace='users'))
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += staticfiles_urlpatterns()

online_store/shop/urls.py
from unicodedata import name
from django.urls import URLPattern, path
from . import views

urlpatterns = [
    path ('products/', views.products_list, name = 'products_list'),
    path ('cart/', views.cart, name='cart'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_item/<int:pk>', views.edit_cart_item, name='edit_cart_item'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('cart/create_order', views.create_order, name='create_order'),
    path('rate_product/<int:pk>', views.rate_product, name='rate_product'),
    path('orders/', views.orders, name = 'orders')
]

online_store/users/urls.py
import imp
from unicodedata import name
from django import views
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
]

online_store/users/models.py
from django.db import models

# Create your models here.

online_store/users/forms.py
from cProfile import label
import email
from re import L
from attr import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .bulma_mixin import BulmaMixin



class SignUpForm(BulmaMixin, UserCreationForm):
    username = forms.CharField(label='Create any username')
    email = forms.EmailField(label='Enter your email adress')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Create secure password')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Repeat password')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class SignInForm(BulmaMixin, AuthenticationForm):
    username = forms.CharField(label='Enter username')
    password = forms.CharField(widget=forms.PasswordInput(),label='Enter password')


    class Meta:
        model = User
        fields = ['username', 'password']

class EditProfileForm(BulmaMixin, forms.ModelForm):
    email = forms.EmailField(label='Write your email')
    first_name = forms.CharField(label='Edit your first name')
    last_name = forms.CharField(label='Edit your last name')
    username = forms.CharField(label='Edit your username')

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'username']
        

class PasswordResetForm(BulmaMixin, PasswordChangeForm):
    old_password = forms.PasswordInput()
    new_password1 = forms.PasswordInput()
    new_password2 = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

online_store/users/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import login, logout, update_session_auth_hash


def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:sign_in')
    form = forms.SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = forms.SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('shop:products_list')
    form = forms.SignInForm()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')


def edit_profile(request):
    form = forms.EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        return redirect('shop:products_list')
    form = forms.EditProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})


def reset_password(request):
    form = forms.PasswordResetForm(request.user, request.POST)

    if request.method == 'POST' and form.is_valid():
        user = form.save()
        update_session_auth_hash(request, user)
        return redirect('users:sign_in')
    form = forms.PasswordResetForm(request.user)
    return render(request, 'reset_password.html', {'form': form})

online_store/users/templates/reset_password.html
{% extends 'base_layout.html' %}
{% block auth %}
<div class="columns is-centered">
    <div class="column is-4">
        <div class="box has-background-info-light">
            <form class="form" method="post" enctype="multipart/form-data">
                <div class="title has-text-centered is-2">Reset password</div>
                {% csrf_token %}

                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
                {% endfor %}
                <button class="button is-primary is-fullwidth" type="submit">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

online_store/users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block auth %}
    <div class="columns is-centered" style="margin-top: 6%">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Sign in</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">
                            {{ field.label }}
                            </label>
                            <div class="control">
                            {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                    <div class="title is-5 mt-4">Don't have an account?</div>
                    <a href="{% url 'users:sign_up' %}">Move to register page -></a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

online_store/users/templates/sign_up.html
{% extends 'base_layout.html' %}

{% block auth %}
    <div class="columns is-centered" style="margin-top: 6%">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form  has-text-centered" method="post">
                    <h1 class="title is-size-2 has-text-centered">Sign up</h1>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">
                            {{ field.label }}
                            </label>
                            <div class="control">
                            {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth">
                        Submit
                    </button>
                    <div class="title is-5 mt-4">Arleady have an account?</div>
                    <a href="{% url 'users:sign_in' %}">Move to login--></a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}